apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: q4t3bwta1-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/q4t3bwta1-dotnet-basic-gitops